from __future__ import annotations

from typing import Any

SCENARIO_TERMINAL_STATUSES = {"passed", "failed"}

SCENARIO_STEP_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "stepId": {"type": "string"},
        "kind": {
            "type": "string",
            "enum": [
                "status",
                "health_probe",
                "scene_snapshot",
                "scene_open",
                "assert_scene",
                "project_refresh",
                "console_tail",
                "console_grep",
                "playmode_set",
                "wait",
                "wait_for_playmode_state",
                "assert_playmode_state",
                "game_view_screenshot",
                "compile_player_scripts",
                "tests_run_editmode",
                "tests_run_playmode",
                "game_view_configure",
                "project_action",
                "project_defined_hook",
                "project_defined_hook_poll_until",
            ],
        },
        "operation": {
            "type": "string",
            "description": "Alias for kind. Supported so scenario JSON can use operation-style step records.",
            "enum": [
                "status",
                "health_probe",
                "scene_snapshot",
                "scene_open",
                "assert_scene",
                "project_refresh",
                "console_tail",
                "console_grep",
                "playmode_set",
                "wait",
                "wait_for_playmode_state",
                "assert_playmode_state",
                "game_view_screenshot",
                "compile_player_scripts",
                "tests_run_editmode",
                "tests_run_playmode",
                "game_view_configure",
                "project_action",
                "project_defined_hook",
                "project_defined_hook_poll_until",
            ],
        },
        "action": {
            "type": "string",
            "enum": ["enter", "exit", "pause", "resume"],
        },
        "dependsOn": {
            "type": "array",
            "items": {"type": "string"},
        },
        "runIfStepPassed": {
            "type": "array",
            "items": {"type": "string"},
        },
        "durationSeconds": {
            "type": "number",
            "minimum": 0.0,
        },
        "timeoutSeconds": {
            "type": "number",
            "minimum": 0.1,
        },
        "expectedPlaymodeState": {
            "type": "string",
            "enum": ["edit", "playing", "paused", "transitioning"],
        },
        "scenePath": {
            "type": "string",
            "description": "Project-relative Assets/... scene path to open before subsequent validation steps.",
        },
        "allowDirtySceneDiscard": {
            "type": "boolean",
            "default": False,
            "description": "When true, allow unity.scene.open to discard unsaved open-scene changes.",
        },
        "expectedName": {"type": "string"},
        "expectedPath": {"type": "string"},
        "requiredRootNames": {
            "type": "array",
            "items": {"type": "string"},
        },
        "allowDirty": {"type": "boolean", "default": True},
        "limit": {
            "type": "integer",
            "minimum": 0,
            "description": "Per-step item limit. Omit or use 0 to apply the step default.",
        },
        "pattern": {"type": "string"},
        "regex": {"type": "boolean"},
        "ignoreCase": {"type": "boolean"},
        "includeStackTraces": {"type": "boolean"},
        "includeTypes": {
            "type": "array",
            "items": {"type": "string"},
        },
        "fileName": {"type": "string"},
        "includeImage": {"type": "boolean"},
        "maxResolution": {"type": "integer", "minimum": 1},
        "target": {"type": "string"},
        "optionFlags": {"type": "array", "items": {"type": "string"}},
        "extraDefines": {"type": "array", "items": {"type": "string"}},
        "name": {"type": "string"},
        "width": {"type": "integer", "minimum": 1},
        "height": {"type": "integer", "minimum": 1},
        "group": {"type": "string"},
        "label": {"type": "string"},
        "allowCreateCustomSize": {"type": "boolean"},
        "forceAssetRefresh": {"type": "boolean"},
        "resolvePackages": {"type": "boolean"},
        "rerunHealthProbe": {"type": "boolean"},
        "hookName": {"type": "string"},
        "hookPayloadJson": {"type": "string"},
        "startPayload": {"type": "object"},
        "startPayloadJson": {"type": "string"},
        "pollPayload": {"type": "object"},
        "pollPayloadJson": {"type": "string"},
        "passWhen": {
            "type": "string",
            "description": "Poll-until predicate using payload.<field> == 'value'.",
        },
        "failWhen": {
            "type": "string",
            "description": "Poll-until predicate using payload.<field> == 'value'.",
        },
        "continueWhen": {
            "type": "string",
            "description": "Optional poll-until predicate using payload.<field> == 'value'. A payload status of not_started also keeps waiting unless passWhen or failWhen explicitly matches it.",
        },
        "intervalSeconds": {"type": "number", "minimum": 0.0, "default": 2.0},
        "promotePayloadFields": {
            "type": "array",
            "items": {"type": "string"},
        },
        "terminalScreenshot": {"type": "boolean", "default": False},
        "terminalConsoleTail": {"type": "boolean", "default": False},
        "continueToCleanupOnFail": {"type": "boolean", "default": True},
        "actionId": {"type": "string"},
        "projectAction": {"type": "string"},
        "payload": {"type": "object"},
        "payloadJson": {"type": "string"},
        "allowMutating": {"type": "boolean", "default": False},
    },
    "anyOf": [{"required": ["kind"]}, {"required": ["operation"]}],
}

SCENARIO_DEFINITION_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "description": {"type": "string"},
        "stopOnFirstFailure": {"type": "boolean", "default": True},
        "steps": {
            "type": "array",
            "items": SCENARIO_STEP_SCHEMA,
            "minItems": 1,
        },
        "cleanupSteps": {
            "type": "array",
            "items": SCENARIO_STEP_SCHEMA,
            "description": "Optional finally-style steps appended to the scenario and still run after a body failure when stopOnFirstFailure is true.",
        },
    },
    "required": ["name", "steps"],
}
