from __future__ import annotations

from typing import Any

OPERATION_LIFECYCLE_POLICIES: dict[str, dict[str, Any]] = {
    "unity.status": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.capabilities.get": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.health.probe": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.build_target.get": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.build_target.switch": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "retry_on_lifecycle_reset": True,
    },
    "unity.project.refresh": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
        "post_reset_recovery_cap_ms": 180000,
    },
    "unity.package.install_test_framework": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
        "post_reset_recovery_cap_ms": 300000,
    },
    "unity.edm4u.resolve": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
        "post_reset_recovery_cap_ms": 300000,
    },
    "unity.sdk.dependency.verify": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": False,
        "idle_stable_cycles_after": 1,
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.scene.snapshot": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.scene.assert": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.console.grep": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.scenario.validate": {
        "retry_on_lifecycle_reset": True,
        "retry_on_transport_response_missing": True,
        "retry_on_transport_connect_failed": True,
    },
    "unity.compile.player_scripts": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "post_reset_recovery_cap_ms": 180000,
    },
    "unity.compile.matrix": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "post_reset_recovery_cap_ms": 300000,
    },
    "unity.build_player": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "post_reset_recovery_cap_ms": 600000,
    },
    "unity.tests.run_editmode": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "post_reset_recovery_cap_ms": 300000,
    },
    "unity.tests.run_playmode": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "post_reset_recovery_cap_ms": 300000,
    },
    "unity.playmode.set": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
        "post_reset_recovery_cap_ms": 180000,
    },
    "unity.game_view.configure": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": True,
        "idle_stable_cycles_after": 2,
    },
    "unity.game_view.screenshot": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": False,
        "idle_stable_cycles_after": 1,
    },
    "unity.scenario.run": {
        "activate_unity": True,
        "wait_for_idle_before": True,
        "wait_for_idle_after": False,
        "idle_stable_cycles_after": 1,
        "post_reset_recovery_cap_ms": 600000,
    },
}
